NewCms/NewCms/Controllers/NewsPageController.cs
using DataLayer;
using DataLayer.Context;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Security;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Generator;

namespace NewCms.Controllers
{
    public class NewsPageController : Controller
    {
        NCmsContext db = new NCmsContext();
        IPageGroupRepasitory pageGroupRepasitory;
        IPageRepasitory pageRepasitory;
        IPageCommentRepasitory commentRepasitory;
        public NewsPageController()
        {
            pageGroupRepasitory = new PageGroupRepasitory(db);
            pageRepasitory = new PageRepasitory(db);
            commentRepasitory = new PageCommentRepasitory(db);
        }
        // GET: NewsPage
        public ActionResult ShowNewsGroup()
        {
            return PartialView(pageGroupRepasitory.GetPageGroupTitleAndPageCount());
        }
        public ActionResult ShowGroupTitleInMeno()
        {
            return PartialView(pageGroupRepasitory.GetAllPageGroup());
        }
        public ActionResult ShowNewsMaxVisit()
        {
            return PartialView(pageRepasitory.GetPageMaxVisted());
        }
        public ActionResult ShowLatesNews()
        {
            return PartialView(pageRepasitory.GetLatesPage());
        }
        public ActionResult ArchiveNews()
        {
            return View(pageRepasitory.GetAllPage());
        }

        [Route("Group/{title}/{id}")]
        public ActionResult ShowNewsPageByGroupId(string title,int id)
        {
            ViewBag.name=title;
            return View(pageRepasitory.GetPageByGroupId(id));
        }
        [Route("News/{id}")]
        public ActionResult ShowPageNews(int id)
        {
            var page = pageRepasitory.GetPageById(id);
            if (page == null)
            {
               return HttpNotFound();
            }
            page.Visit += 1;
            pageRepasitory.UpdatePage(page);
            pageRepasitory.Save();
            return View(page);
        }

        public ActionResult AddComment(int id, string name, string email, string comment)
        {
            PageComment addComment = new PageComment()
            {
                PageID = id,
                Name=name,
                Email=email,
                CommentText=comment,
                CreatedDate=DateTime.Now

             };
            commentRepasitory.AddComment(addComment);
            
            return PartialView("ShowComment", commentRepasitory.GetCommentByPageId(id)); 
        }
        public ActionResult ShowComment(int id)
        {
            return PartialView(commentRepasitory.GetCommentByPageId(id));
        }
    }
}

NewCms/NewCms/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title> سایت خبری برنامه نویسان </title>
    <base href="">
    <meta name="googlebot" content="index,follow">
    <meta name="robots" content="noodp,noydir">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/Content/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/style.css">
    <script src="/Content/js/jquery.min.js"></script>
</head>
<body>
    <script src="/Content/js/modernizr.js"></script>

    <!-- Top Menu -->
    <div class="top-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-5">
                    <ul>
                        <li><a href=""><i class="fa fa-home"></i></a></li>
                        <li><a href=""><i class="fa fa-question-circle"></i></a></li>
                        <li><a href=""><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-7">
                    <span>امروز : @DateTime.Now.Toshamsi()</span>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Menu -->
    <!-- header -->
    <header class="main-header">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <a href="" class="logo"><img src="/Content/img/logo.png" alt="" title=""></a>
                    <div class="left-side">
                        <h1><a href="">سایت خبری برنامه نویسان</a></h1>
                        <h2> پایگاه اطلاع رسانی و خبری</h2>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <form action="/Search/" method="get" class="border-radius">
                        <input class="border-radius" type="text" name="q"     placeholder=" جستجو کنید ... ">
                        <button><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </header>
    <!-- End Header -->
    <!-- menu -->
    <nav class="main-menu">
        <div class="container">
            <span><i class="fa fa-th-list"></i></span>
            <ul>
                <li><a href=""> صفحه اصلی </a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a href="">  @User.Identity.Name خوش آمدید . </a></li>
                    <li><a href="/Account/SignOut">خروج </a></li>
                    
                }
                else
                {
                    <li><a href="/Account/Login"> ورود به سایت </a></li>
                }

                <li>
                    <span>گروه های خبری</span>
                    @Html.Action("ShowGroupTitleInMeno", "NewsPage")
                </li>
            </ul>
        </div>
    </nav>
    <!-- End menu -->

    <div class="container margin-top-30">
        <div class="row">

            <aside class="col-md-4 col-sm-12 col-xs-12 pull-right">

                <section class="category-section border-radius">
                   @Html.Action("ShowNewsGroup","NewsPage")
                </section>
                <!-- most views news -->
                <section class="last-news-side border-radius">
                  @Html.Action("ShowNewsMaxVisit","NewsPage")
                </section>
                <!-- end most views news -->
            </aside>

            <div class="col-md-8 col-sm-12 col-xs-12 ">
                @RenderBody()

            </div>

            

        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <section class="access-links">
                        <header> دسترسی سریع </header>
                        <ul>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> راهنمای سایت  </a></li>
                            <li><a href=""> پیوندهای سایت </a></li>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> قوانین سایت  </a></li>
                            <li><a href=""> راهنمای سایت  </a></li>
                        </ul>
                    </section>
                </div>
                <div class="col-md-5 col-md-offset-1 col-sm-12 col-xs-12">
                    <div class="socials">
                        <span> شبکه های اجتماعی  سایت</span>
                        <a href=""><i class="fa fa-facebook"></i></a>
                        <a href=""><i class="fa fa-twitter"></i></a>
                        <a href=""><i class="fa fa-paper-plane"></i></a>
                        <a href=""><i class="fa fa-google-plus"></i></a>
                        <div class="clearfix"></div>
                    </div>
                    <p>
                        تمامی حقوق مادی و معنوی این طرح متعلق به آموزشگاه برنامه نویسان می باشد و کپی برداری از این طرح غیر اخلاقی می باشد.
                    </p>
                </div>
            </div>
        </div>
    </footer>
  
    <script src="/Content/js/bootstrap.min.js"></script>
    <script src="/Content/js/owl.carousel.js"></script>
    <script src="/Content/js/script.js"></script>
    @RenderSection("scripts",false)
</body>
</html>